version: '2.2'
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000  # Cube.js API and Developer Playground
      - 3000:3000  # Dashboard app, if created
      - 3307:3307 # SQL Port
      - 5432:5432 # PostgreSQL Cube SQL API port - new https://cube.dev/docs/config/downstream/superset#enable-cube-sql-api-self-hosted-cube
    environment:
      # Cube type for mongo bi connector
      CUBEJS_DB_TYPE: mongobi
      # The MongoBI connector host. If using on local machine, it should be either `localhost` or `127.0.0.1`:
      CUBEJS_DB_HOST: mongo-bi
      # The default port of the MongoBI connector service
      CUBEJS_DB_PORT: 3307
      
      CUBEJS_DB_NAME: test-clinic # My mongodb database
      CUBEJS_DB_USER: root # My mongodb user 
      CUBEJS_DB_PASS: secret # My mongodb password
      CUBEJS_DEV_MODE: true
      CUBEJS_EXTERNAL_DEFAULT: true
      CUBEJS_WEB_SOCKETS: true
      CUBEJS_API_SECRET: secret
      CUBEJS_SQL_USER: root
      CUBEJS_SQL_PASSWORD: secret
      CUBEJS_SQL_PORT: 3306 # Old version 
      CUBEJS_PG_SQL_PORT: 5432
    volumes:
      - .:/cube/conf
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017  
      SCHEMA_REFRESH: 60
  mongo-bi:
    build:
      dockerfile: Dockerfile.dev
      context: ./superset
    container_name: mongo-bi
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017  
      SCHEMA_REFRESH: 60

  superset:
    build:
      dockerfile: Dockerfile.dev
      context: ./superset
    container_name: superset
    ports:
      - 8080:8088
   