version: '2.2'
services:
  cube:
    image: cubejs/cube:latest
    ports:
      - 4000:4000  # Cube.js API and Developer Playground
      - 3000:3000  # Dashboard app, if created
    environment:
      CUBEJS_DB_TYPE: mongobi
      CUBEJS_DB_HOST: mongobi
      CUBEJS_DB_NAME: test-clinic
      CUBEJS_DB_PORT: 3307
      CUBEJS_DB_USER: root
      CUBEJS_DB_PASS: secret
      CUBEJS_DEV_MODE: true
      CUBEJS_EXTERNAL_DEFAULT: true
      CUBEJS_WEB_SOCKETS: true
      CUBEJS_API_SECRET: secret
      CUBEJS_SQL_USER: root
      CUBEJS_SQL_PASSWORD: secret
      CUBEJS_SQL_PORT: 3306
    volumes:
      - .:/cube/conf
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017  
      SCHEMA_REFRESH: 60
  mongobi:
    build:
      dockerfile: Dockerfile.dev
      context: ./superset
    container_name: mongobi
    environment:
      MONGODB_HOST: mongodb
      MONGODB_PORT: 27017  
      SCHEMA_REFRESH: 60

  superset:
    build:
      dockerfile: Dockerfile.dev
      context: ./superset
    container_name: superset
    ports:
      - 8080:8088
   