dbt_cube:
  outputs:
    dev:
      type: postgres
      host: postgres
      user: root
      password: secret
      port: 5432
      dbname: semantic_layer
      schema: public
      threads: 1
  target: dev
  